// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiHack_RitehKromanjonci.Data;

#nullable disable

namespace RiHack_RitehKromanjonci.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231007100938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiHack_RitehKromanjonci.Models.DailyGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EatingPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EatingPlanId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("DailyGoals");
                });

            modelBuilder.Entity("RiHack_RitehKromanjonci.Models.EatingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("EatingPlans");
                });

            modelBuilder.Entity("RiHack_RitehKromanjonci.Models.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("RiHack_RitehKromanjonci.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyGoalId")
                        .HasColumnType("integer");

                    b.Property<int>("EatingPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YourProgressId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DailyGoalId");

                    b.HasIndex("EatingPlanId");

                    b.HasIndex("TrainingPlanId");

                    b.HasIndex("YourProgressId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RiHack_RitehKromanjonci.Models.YourProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("YourProgresses");
                });

            modelBuilder.Entity("RiHack_RitehKromanjonci.Models.DailyGoal", b =>
                {
                    b.HasOne("RiHack_RitehKromanjonci.Models.EatingPlan", "EatingPlans")
                        .WithMany()
                        .HasForeignKey("EatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiHack_RitehKromanjonci.Models.TrainingPlan", "TrainingPlans")
                        .WithMany()
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EatingPlans");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("RiHack_RitehKromanjonci.Models.User", b =>
                {
                    b.HasOne("RiHack_RitehKromanjonci.Models.DailyGoal", "DailyGoals")
                        .WithMany()
                        .HasForeignKey("DailyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiHack_RitehKromanjonci.Models.EatingPlan", "EatingPlans")
                        .WithMany()
                        .HasForeignKey("EatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiHack_RitehKromanjonci.Models.TrainingPlan", "TrainingPlans")
                        .WithMany()
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiHack_RitehKromanjonci.Models.YourProgress", "Progress")
                        .WithMany()
                        .HasForeignKey("YourProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyGoals");

                    b.Navigation("EatingPlans");

                    b.Navigation("Progress");

                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
